[package]
name = "lib_stripe"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stripe = { version = "0.14", features = ["runtime-tokio-hyper"] }
my_macros = { path = "../my_macros" }
